const seed = [
  { code:'CP.01', category:'Công tác đất', description:'Đào đất móng bằng máy, đất cấp II', unit:'m³', quantity:148.5, price:92000, formula:'Dài × Rộng × Sâu × Số lượng', dims:'15 × 11 × 0,9 × 1', note:'Đã trừ thể tích đài móng' },
  { code:'BT.01', category:'Bê tông', description:'Bê tông lót móng M100', unit:'m³', quantity:42.5, price:1250000, formula:'Dài × Rộng × Sâu × Số lượng', dims:'42,5 × 1', note:'Theo bản vẽ KC-03' },
  { code:'BT.02', category:'Bê tông', description:'Bê tông móng M300', unit:'m³', quantity:186.2, price:1680000, formula:'Theo cấu kiện', dims:'Tổng hợp đài móng M1–M8', note:'Chưa gồm bê tông cổ cột' },
  { code:'CT.01', category:'Cốt thép', description:'Cốt thép móng CB400-V', unit:'kg', quantity:12480, price:18900, formula:'Chiều dài × Trọng lượng đơn vị', dims:'Tổng hợp thống kê thép', note:'Đã tính nối chồng theo chi tiết' },
  { code:'VK.01', category:'Ván khuôn', description:'Ván khuôn móng', unit:'m²', quantity:326.4, price:285000, formula:'Chu vi × Chiều cao × Số cấu kiện', dims:'Tổng hợp các đài móng', note:'Diện tích tiếp xúc bê tông' }
];
const demoMode = location.protocol === 'file:' || new URLSearchParams(location.search).has('demo');
const config=window.QS_PRO_SUPABASE_CONFIG||{},configured=/^https:\/\/.+/.test(config.url||'')&&(config.anonKey||'').length>20;
const supabaseClient=configured&&window.supabase?.createClient?window.supabase.createClient(config.url,config.anonKey):null;
const defaultSettings={waste:0,overhead:5,contingency:2,vat:8};
let user=null,passwordRecovery=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery',filterText='',activeCategory='Tất cả',saveTimer;
let projects=read('qspro-projects',null),activeProjectId=read('qspro-active-project','');
if(!Array.isArray(projects)||!projects.length){const legacyProject=read('qspro-project',{name:'Riverside Residence',type:'Nhà ở cao tầng',location:'TP. Hồ Chí Minh'});projects=[{id:'prj-'+Date.now().toString(36),project:legacyProject,items:read('qspro-items',seed),steelBars:read('qspro-steel-bars',[]),settings:read('qspro-settings',defaultSettings),updatedAt:null}];activeProjectId=projects[0].id}
let activeRecord=projects.find(x=>x.id===activeProjectId)||projects[0];activeProjectId=activeRecord.id;
let project=activeRecord.project||{name:'Dự án mới',type:'Dự án xây dựng',location:'Chưa cập nhật'},items=activeRecord.items||[],steelBars=activeRecord.steelBars||[],settings={...defaultSettings,...activeRecord.settings};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(Number(n)||0),cash=n=>fmt(Math.round(Number(n)||0)),total=()=>items.reduce((s,x)=>s+(+x.quantity||0)*(+x.price||0),0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function showMessage(text,error=false){const el=$('#authMessage');el.textContent=text;el.classList.toggle('error',error);el.hidden=false}
function snapshotActiveProject(){const record=projects.find(x=>x.id===activeProjectId);if(record)Object.assign(record,{project:{...project},items:items.map(x=>({...x})),steelBars:steelBars.map(x=>({...x})),settings:{...settings},updatedAt:new Date().toISOString()})}
function workspacePayload(){snapshotActiveProject();return{projects,activeProjectId,items,steelBars,project,settings}}
async function saveCloud(){if(!user||demoMode)return;const {error}=await supabaseClient.from('qspro_workspaces').upsert({user_id:user.id,workspace:workspacePayload(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)toast('Chưa đồng bộ được dữ liệu. Hãy kiểm tra kết nối rồi thử lại.')}
function persist(){snapshotActiveProject();if(demoMode){localStorage.setItem('qspro-projects',JSON.stringify(projects));localStorage.setItem('qspro-active-project',activeProjectId);localStorage.setItem('qspro-items',JSON.stringify(items));localStorage.setItem('qspro-steel-bars',JSON.stringify(steelBars));localStorage.setItem('qspro-project',JSON.stringify(project));localStorage.setItem('qspro-settings',JSON.stringify(settings));return}if(!user)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,500)}
function loadWorkspace(workspace={}){if(Array.isArray(workspace.projects)&&workspace.projects.length){projects=workspace.projects.map((x,i)=>({...x,id:x.id||'prj-migrated-'+i,project:x.project||{name:'Dự án mới',type:'Dự án xây dựng',location:'Chưa cập nhật'},items:Array.isArray(x.items)?x.items:[],steelBars:Array.isArray(x.steelBars)?x.steelBars:[],settings:{...defaultSettings,...x.settings}}));activeProjectId=projects.some(x=>x.id===workspace.activeProjectId)?workspace.activeProjectId:projects[0].id}else{const legacyProject=workspace.project||{name:'Dự án mẫu Riverside Residence',type:'Nhà ở cao tầng',location:'TP. Hồ Chí Minh'};projects=[{id:'prj-'+Date.now().toString(36),project:legacyProject,items:Array.isArray(workspace.items)?workspace.items:seed,steelBars:Array.isArray(workspace.steelBars)?workspace.steelBars:[],settings:{...defaultSettings,...workspace.settings},updatedAt:null}];activeProjectId=projects[0].id}selectActiveProject()}
function selectActiveProject(){const record=projects.find(x=>x.id===activeProjectId)||projects[0];if(!record)return;activeProjectId=record.id;project=record.project;items=record.items;steelBars=record.steelBars;settings={...defaultSettings,...record.settings}}
function renderProjectList(){const list=$('#projectList');if(!list)return;list.innerHTML=projects.map(record=>'<div class="project-row '+(record.id===activeProjectId?'is-active':'')+'"><button class="project-link" data-project-id="'+esc(record.id)+'" title="Mở '+esc(record.project.name)+'"><i class="project-dot '+(record.items.length?'':'dot-gray')+'"></i>'+esc(record.project.name)+'<span>'+record.items.length+'</span></button><button class="project-delete" data-delete-project="'+esc(record.id)+'" aria-label="Xóa dự án '+esc(record.project.name)+'" title="Xóa dự án">×</button></div>').join('')}
function switchProject(id){if(!projects.some(x=>x.id===id)||id===activeProjectId)return;persist();activeProjectId=id;selectActiveProject();filterText='';activeCategory='Tất cả';$('#searchBOQ').value='';render();navigate('takeoff')}
function navigate(page){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===`page-${page}`));document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.page===page));const names={overview:'Tổng quan',takeoff:'Bóc tách khối lượng',steel:'Tính thép từ PDF',skills:'Kỹ năng QS',library:'Thư viện tài liệu',account:'Tài khoản & gói'};$('#crumb').textContent=names[page];history.replaceState(null,'',`#${page}`);window.scrollTo(0,0);if(page==='steel')renderSteelRows()}
document.querySelectorAll('[data-page]').forEach(e=>e.addEventListener('click',()=>navigate(e.dataset.page)));
function render(){
  $('#projectTitle').textContent=project.name;$('#projectMeta').textContent=`${project.type} · ${project.location}`;
  renderProjectList();$('#projectCount').textContent=projects.length;$('#activeProjectCount').textContent=projects.filter(x=>x.items.length>0).length;
  $('#overviewProjectTitle').textContent=project.name;$('#overviewProjectMeta').textContent=`${project.type} · ${project.location}`;$('#overviewProjectItems').textContent=items.length;$('#overviewProjectValue').textContent=cash(total());$('#overviewProjectStatus').textContent=items.length?'ĐANG CÓ BOQ':'CHƯA CÓ BOQ';$('#overviewProjectFooter').textContent=items.length?items.length+' công tác đã lưu':'Chưa có công tác trong BOQ';
  const categories=['Tất cả',...new Set(items.map(i=>i.category||'Khác'))];$('#categoryFilters').innerHTML=categories.map(c=>`<button class="filter-chip ${activeCategory===c?'selected':''}" data-category="${esc(c)}">${esc(c)} <span>${c==='Tất cả'?items.length:items.filter(i=>i.category===c).length}</span></button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;render()});
  const shown=items.map((x,i)=>({...x,_i:i})).filter(x=>(activeCategory==='Tất cả'||x.category===activeCategory)&&(`${x.code} ${x.description} ${x.category}`.toLowerCase().includes(filterText)));
  $('#boqBody').innerHTML=shown.map(x=>`<tr><td class="code-cell"><span>${esc(x.code)}</span></td><td><div class="work-name">${esc(x.description)}</div><div class="work-detail">${esc(x.note||'')}</div></td><td><span class="category-pill">${esc(x.category||'Khác')}</span></td><td class="unit-cell">${esc(x.unit)}</td><td class="numeric">${fmt(x.quantity)}</td><td class="numeric">${cash(x.price)}</td><td class="numeric amount-cell">${cash(x.quantity*x.price)}</td><td><button class="row-more" title="Thao tác" data-row="${x._i}">•••</button></td></tr>`).join('');$('#emptyState').hidden=shown.length!==0;
  const sub=total(),waste=sub*(+settings.waste||0)/100,overhead=(sub+waste)*(+settings.overhead||0)/100,contingency=(sub+waste+overhead)*(+settings.contingency||0)/100,beforeVat=sub+waste+overhead+contingency,vat=beforeVat*(+settings.vat||0)/100;
  $('#boqCount').textContent=String(items.length).padStart(2,'0');$('#totalItems').innerHTML=`${String(items.length).padStart(2,'0')} <small>hạng mục</small>`;$('#boqTotal').textContent=cash(sub);$('#grandTotal').textContent=cash(beforeVat+vat);$('#grandTotalCopy').textContent=cash(beforeVat+vat);$('#subtotal').textContent=cash(sub);$('#wasteTotal').textContent=cash(waste);$('#overheadTotal').textContent=cash(overhead);$('#contingencyTotal').textContent=cash(contingency);$('#vatTotal').textContent=cash(vat);$('#totalCost').innerHTML=sub?`${cash(beforeVat+vat)} <small>VND</small>`:'—';$('#overviewCostProject').textContent=project.name;$('#scopeCount').textContent=items.length;persist();
  for(const key of ['waste','overhead','contingency','vat']){const input=$(`[data-setting="${key}"]`);if(input&&document.activeElement!==input)input.value=settings[key]}persist();
}
function setAuthMode(mode){const signup=mode==='signup',recovery=mode==='recovery';document.querySelector('.auth-mode').hidden=recovery;$('#resetPassword').hidden=recovery;document.querySelectorAll('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#authHeading').textContent=recovery?'Đặt mật khẩu mới':signup?'Tạo tài khoản QS Pro':'Đăng nhập workspace';$('#authDescription').textContent=recovery?'Chọn mật khẩu mới để bảo vệ tài khoản của bạn.':signup?'Tạo không gian riêng cho dự án và dữ liệu QS của bạn.':'Dùng email và mật khẩu để tiếp tục công việc.';$('#authSubmit').innerHTML=recovery?'Lưu mật khẩu mới <span>→</span>':signup?'Tạo tài khoản <span>→</span>':'Đăng nhập <span>→</span>';$('#authForm [name="password"]').autocomplete=signup||recovery?'new-password':'current-password';$('#authMessage').hidden=true;}
document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));
async function enterWorkspace(authUser){if(!demoMode&&authUser&&user?.id===authUser.id&&!$('#appShell').hidden)return;user=authUser;$('#authScreen').hidden=true;$('#appShell').hidden=false;const accountName=demoMode?'Giám đốc dự án':'Chủ workspace',accountEmail=demoMode?'Bản demo trên thiết bị này':(user?.email||'');$('#profileEmail').textContent=accountEmail;$('#profileName').textContent=accountName;$('#accountName').textContent=accountName;$('#accountEmail').textContent=accountEmail;$('#accountPageEmail').textContent=accountEmail;$('#accountMenuToggle').textContent='GD';if(!demoMode){const {data,error}=await supabaseClient.from('qspro_workspaces').select('workspace').eq('user_id',user.id).maybeSingle();if(error){await supabaseClient.auth.signOut();user=null;$('#appShell').hidden=true;$('#authScreen').hidden=false;showMessage('Không tải được dữ liệu workspace. Kiểm tra cấu hình bảng và chính sách bảo mật rồi thử lại.',true);return}if(data?.workspace){loadWorkspace(data.workspace);if(!Array.isArray(data.workspace.projects))persist()}else{loadWorkspace({project:{name:'Dự án mẫu Riverside Residence',type:'Nhà ở cao tầng',location:'TP. Hồ Chí Minh'},items:seed,steelBars:[],settings:defaultSettings});persist()}}render();const start=location.hash.slice(1);if(['overview','takeoff','steel','skills','library','account'].includes(start))navigate(start)}
if(demoMode){enterWorkspace(null)}else{ $('#authScreen').hidden=false;if(!configured||!supabaseClient){$('#authSetup').hidden=false;$('#authSubmit').disabled=true;$('#resetPassword').disabled=true;}else{supabaseClient.auth.getSession().then(({data})=>{if(passwordRecovery){$('#authScreen').hidden=false;setAuthMode('recovery');if(data.session)$('#authForm [name="email"]').value=data.session.user.email||''}else if(data.session)enterWorkspace(data.session.user)});supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session&&$('#appShell').hidden&&!passwordRecovery)setTimeout(()=>enterWorkspace(session.user),0);else if(!session){user=null;$('#appShell').hidden=true;$('#authScreen').hidden=false}});if(passwordRecovery)setAuthMode('recovery')}}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();if(!configured){showMessage('Hệ thống đăng nhập chưa được cấu hình. Chưa có mật khẩu nào được gửi.',true);return}const form=new FormData(e.currentTarget),email=String(form.get('email')).trim(),password=String(form.get('password')),signup=document.querySelector('[data-auth-mode="signup"]').classList.contains('active'),button=$('#authSubmit');button.disabled=true;button.textContent=passwordRecovery?'Đang cập nhật…':signup?'Đang tạo tài khoản…':'Đang đăng nhập…';$('#authMessage').hidden=true;try{if(passwordRecovery){const {error}=await supabaseClient.auth.updateUser({password});if(error)throw error;passwordRecovery=false;history.replaceState(null,'',location.pathname);setAuthMode('signin');showMessage('Đã cập nhật mật khẩu. Đang mở workspace của bạn.');const {data}=await supabaseClient.auth.getSession();if(data.session)await enterWorkspace(data.session.user)}else{const result=signup?await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabaseClient.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signup&&!result.data.session)showMessage('Đã nhận yêu cầu đăng ký. Hãy mở email xác nhận để kích hoạt tài khoản QS Pro.');else if(result.data.user)await enterWorkspace(result.data.user)}}catch(err){showMessage(err.message||'Không thể đăng nhập. Hãy kiểm tra email và mật khẩu.',true)}finally{button.disabled=false;button.innerHTML=passwordRecovery?'Lưu mật khẩu mới <span>→</span>':signup?'Tạo tài khoản <span>→</span>':'Đăng nhập <span>→</span>'}});
$('#resetPassword').addEventListener('click',async()=>{const email=$('#authForm [name="email"]').value.trim();if(!email){showMessage('Nhập email của bạn trước để nhận liên kết đặt lại mật khẩu.',true);return}if(!configured){showMessage('Dịch vụ tài khoản chưa được kết nối.',true);return}const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin});showMessage(error?error.message:'Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.',!!error)});
async function signOutWorkspace(){if(demoMode){toast('Bản demo cục bộ không có tài khoản để đăng xuất.');return}clearTimeout(saveTimer);await saveCloud();await supabaseClient.auth.signOut()}
$('#signOut').addEventListener('click',signOutWorkspace);$('#accountSignOut').addEventListener('click',signOutWorkspace);
$('#accountMenuToggle').addEventListener('click',()=>{const menu=$('#accountMenu'),open=menu.hidden;menu.hidden=!open;$('#accountMenuToggle').setAttribute('aria-expanded',String(open))});
$('#manageAccountButton').addEventListener('click',()=>{navigate('account');$('#accountMenu').hidden=true;$('#accountMenuToggle').setAttribute('aria-expanded','false')});
document.addEventListener('click',event=>{if(!event.target.closest('.account-menu-wrap')){$('#accountMenu').hidden=true;$('#accountMenuToggle').setAttribute('aria-expanded','false')}});
$('#accountPasswordToggle').addEventListener('click',()=>{const form=$('#accountPasswordForm');form.hidden=!form.hidden;$('#accountPasswordToggle').textContent=form.hidden?'Đổi mật khẩu':'Đóng phần đổi mật khẩu';if(!form.hidden)form.querySelector('[name="newPassword"]').focus()});
$('#accountPasswordForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),password=String(data.get('newPassword')||''),confirmation=String(data.get('confirmPassword')||''),message=$('#accountPasswordMessage'),button=$('#accountPasswordSubmit');message.hidden=false;message.classList.remove('is-error');if(demoMode||!user){message.textContent='Bản demo không có tài khoản thật để đổi mật khẩu.';message.classList.add('is-error');return}if(password.length<8){message.textContent='Mật khẩu mới cần có ít nhất 8 ký tự.';message.classList.add('is-error');return}if(password!==confirmation){message.textContent='Hai mật khẩu chưa khớp. Anh kiểm tra và nhập lại nhé.';message.classList.add('is-error');return}button.disabled=true;button.textContent='Đang cập nhật…';try{const {error}=await supabaseClient.auth.updateUser({password});if(error)throw error;form.reset();message.textContent='Đã cập nhật mật khẩu cho tài khoản này.';toast('Đổi mật khẩu thành công.')}catch(error){message.textContent=error.message||'Chưa đổi được mật khẩu. Hãy đăng nhập lại rồi thử lại.';message.classList.add('is-error')}finally{button.disabled=false;button.innerHTML='Cập nhật mật khẩu <span>→</span>'}});
document.querySelectorAll('[data-plan]').forEach(button=>button.addEventListener('click',()=>{const note=$('#accountPaymentNote');note.innerHTML='<strong>Đã chọn '+esc(button.dataset.plan)+'</strong><span>Đây mới là lựa chọn thử nghiệm. QS Pro chưa tạo đơn hàng hay xác nhận thanh toán; chủ dự án cần cấu hình tài khoản ngân hàng và cách duyệt chuyển khoản trước khi mở bán.</span>';note.scrollIntoView({behavior:'smooth',block:'center'})}));
$('#searchBOQ').addEventListener('input',e=>{filterText=e.target.value.toLowerCase().trim();render()});
function updateItemUnitFields(){const unit=$('#itemUnit').value,manual=['kg','tấn','bộ','cái'].includes(unit),required={length:['m³','m²','m'].includes(unit),width:['m³','m²'].includes(unit),height:unit==='m³',count:!manual};for(const field of ['length','width','height','count']){const input=$(`#itemForm [name="${field}"]`),label=input.closest('[data-dimension-field]'),visible=required[field];label.hidden=!visible;input.disabled=!visible;input.required=visible}const quantity=$('#itemForm [name="quantity"]');quantity.required=manual;$('#quantityHelp').textContent=manual?'Bắt buộc cho đơn vị này; web không suy ra từ kích thước.':'Không bắt buộc nếu tính từ kích thước phía trên.';updateItemFormulaPreview()}
function updateItemFormulaPreview(){const form=$('#itemForm'),unit=$('#itemUnit').value,raw=form.elements.namedItem('quantity').value.trim(),preview=$('#formulaPreview');if(raw!==''){preview.textContent=`Khối lượng nhập trực tiếp = ${fmt(raw)} ${unit}`;return}if(['kg','tấn','bộ','cái'].includes(unit)){preview.textContent=`Đơn vị ${unit} cần nhập khối lượng / số lượng trực tiếp.`;return}const length=Number(form.elements.namedItem('length').value),width=Number(form.elements.namedItem('width').value),height=Number(form.elements.namedItem('height').value),count=Number(form.elements.namedItem('count').value)||1,required=unit==='m³'?[length,width,height]:unit==='m²'?[length,width]:[length];if(required.some(value=>!(value>0))){preview.textContent='Nhập đủ kích thước bắt buộc để xem phép tính.';return}const quantity=unit==='m³'?length*width*height*count:unit==='m²'?length*width*count:length*count,parts=unit==='m³'?[length,width,height,count]:unit==='m²'?[length,width,count]:[length,count];preview.textContent=`${parts.map(fmt).join(' × ')} = ${fmt(quantity)} ${unit}`}
$('#addItem').addEventListener('click',()=>{$('#itemForm').reset();$('#itemForm [name="quantity"]').value='';$('#itemForm [name="price"]').value=0;$('#itemForm [name="count"]').value=1;$('#itemForm [name="formula"]').value='';updateItemUnitFields();$('#itemDialog').showModal()});
$('#itemForm').addEventListener('input',updateItemFormulaPreview);$('#itemUnit').addEventListener('change',updateItemUnitFields);
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),category=f.get('category'),prefix=({'Công tác đất':'CP','Bê tông':'BT','Cốt thép':'CT','Ván khuôn':'VK','Hoàn thiện':'HT','MEP':'MEP'})[category]||'KH',sequence=items.filter(x=>x.category===category).reduce((max,x)=>Math.max(max,Number(String(x.code).split('.').at(-1))||0),0)+1,l=Number(f.get('length'))||0,w=Number(f.get('width'))||0,h=Number(f.get('height'))||0,n=Number(f.get('count'))||1,u=f.get('unit'),direct=String(f.get('quantity')||'').trim(),quantity=direct!==''?Number(direct):u==='m³'?l*w*h*n:u==='m²'?l*w*n:l*n,defaultFormula=direct!==''?`Nhập trực tiếp: ${fmt(quantity)} ${u}`:u==='m³'?`${fmt(l)} × ${fmt(w)} × ${fmt(h)} × ${fmt(n)}`:u==='m²'?`${fmt(l)} × ${fmt(w)} × ${fmt(n)}`:`${fmt(l)} × ${fmt(n)}`;items.push({code:`${prefix}.${String(sequence).padStart(2,'0')}`,category,description:f.get('description'),unit:u,quantity,price:Number(f.get('price'))||0,formula:String(f.get('formula')||'').trim()||defaultFormula,dims:direct!==''?'Nhập trực tiếp':defaultFormula,note:f.get('note')||''});$('#itemDialog').close();render();toast('Đã thêm công tác vào bảng khối lượng.')});
$('#boqBody').addEventListener('click',e=>{const b=e.target.closest('[data-row]');if(!b)return;const i=+b.dataset.row,choice=prompt(`Thao tác với ${items[i].code}: nhập “x” để xóa, hoặc nhập đơn giá mới.`);if(choice===null)return;if(choice.trim().toLowerCase()==='x'){if(confirm('Xóa hạng mục này khỏi BOQ?')){items.splice(i,1);render();toast('Đã xóa hạng mục.')}return}const price=Number(choice);if(Number.isFinite(price)&&price>=0){items[i].price=price;render();toast('Đã cập nhật đơn giá.')}else toast('Nhập “x” để xóa hoặc nhập đơn giá hợp lệ.')});
document.querySelectorAll('[data-setting]').forEach(input=>input.addEventListener('input',()=>{settings[input.dataset.setting]=+input.value||0;render()}));
$('#exportCsv').addEventListener('click',()=>{const rows=[['Mã hiệu','Nhóm công tác','Mô tả','Đơn vị','Khối lượng','Đơn giá (VND)','Thành tiền (VND)','Cách tính','Ghi chú'],...items.map(x=>[x.code,x.category,x.description,x.unit,x.quantity,x.price,x.quantity*x.price,x.formula,x.note])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`QS-Pro-${project.name.replace(/[^\p{L}\p{N}-]+/gu,'-')}-BOQ.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Đã xuất BOQ kèm nhóm, ghi chú và cách tính.')});
$('#newProject').addEventListener('click',()=>{const name=prompt('Tên dự án mới:','Dự án mới');if(!name?.trim())return;const locationName=prompt('Địa điểm dự án:','TP. Hồ Chí Minh')||'Chưa cập nhật',id='prj-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);projects.push({id,project:{name:name.trim(),type:'Dự án xây dựng',location:locationName},items:[],steelBars:[],settings:{...defaultSettings},updatedAt:null});activeProjectId=id;selectActiveProject();activeCategory='Tất cả';filterText='';$('#searchBOQ').value='';render();navigate('takeoff');toast('Đã tạo dự án mới. Dự án cũ vẫn được lưu riêng.')});
$('#projectList').addEventListener('click',event=>{const deleteButton=event.target.closest('[data-delete-project]');if(deleteButton){const id=deleteButton.dataset.deleteProject,record=projects.find(x=>x.id===id);if(!record)return;if(projects.length===1){toast('Cần giữ lại ít nhất một dự án trong workspace.');return}if(!confirm(`Xóa dự án “${record.project.name}” và dữ liệu BOQ/thép của dự án này?`))return;persist();projects=projects.filter(x=>x.id!==id);if(activeProjectId===id){activeProjectId=projects[0].id;selectActiveProject()}render();toast('Đã xóa dự án đã chọn.');return}const projectButton=event.target.closest('[data-project-id]');if(projectButton)switchProject(projectButton.dataset.projectId)});
$('#measureGuide').addEventListener('click',()=>toast('Quy trình: xác nhận phiên bản bản vẽ → phân nhóm công tác → đo bóc cấu kiện → ghi rõ giả định → kiểm tra chéo.'));
$('#termsGuide').addEventListener('click',()=>toast('BOQ: Bảng khối lượng · BUA: Tổng diện tích sàn · VO: Phát sinh hợp đồng · QS: Kỹ sư khối lượng.'));
$('#drawingInfo').addEventListener('click',()=>navigate('steel'));
$('#today').textContent=new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date());
// PDF-first rebar takeoff. PDF bytes remain in this browser tab; only the schedule syncs with the workspace.
const steelDiameters=[6,8,10,12,14,16,18,20,22,25,28,32,36,40];
let pdfjsModule=null,pdfDocument=null,pdfPageNumber=1,pdfZoom=1,pdfMode='',pdfPoints=[],pdfPageCalibrations=new Map(),pdfPageMarks=new Map(),pdfRenderToken=0;
const pdfCanvas=$('#pdfCanvas'),pdfMarkup=$('#pdfMarkup'),pdfStack=$('#pdfCanvasStack');
function steelUnitWeight(d){return (Number(d)||0)**2/162}
function steelRowTotals(row){const length=Math.max(0,Number(row.length)||0),count=Math.max(0,Number(row.count)||0),unit=steelUnitWeight(row.diameter);return{length,count,unit,totalLength:length*count,totalKg:length*count*unit}}
function updateSteelSummary(){
  const summary=steelBars.map(steelRowTotals),bars=summary.reduce((a,x)=>a+x.count,0),length=summary.reduce((a,x)=>a+x.totalLength,0),kg=summary.reduce((a,x)=>a+x.totalKg,0);
  $('#steelTotalBars').textContent=fmt(bars);$('#steelTotalLength').textContent=fmt(length);$('#steelTotalKg').textContent=fmt(kg);$('#steelTotalTon').textContent=fmt(kg/1000)+' tấn';
  $('#steelEmptyState').hidden=steelBars.length>0;
  const groups=new Map();steelBars.forEach((row,i)=>{const d=Number(row.diameter)||0;groups.set(d,(groups.get(d)||0)+summary[i].totalKg)});
  $('#steelBreakdown').innerHTML=[...groups.entries()].sort((a,b)=>a[0]-b[0]).map(([d,totalKg])=>'<span class="steel-breakdown-chip">Ø'+d+' <strong>'+fmt(totalKg)+' kg</strong></span>').join('');
}
function renderSteelRows(){
  const rows=$('#steelRows');if(!rows)return;
  rows.innerHTML=steelBars.map((row,index)=>{const totals=steelRowTotals(row),diameter=steelDiameters.includes(Number(row.diameter))?Number(row.diameter):12,id=esc(row.id);
    return '<tr data-steel-row="'+id+'"><td><input data-steel-field="mark" aria-label="Ký hiệu thanh" value="'+esc(row.mark||('T'+String(index+1).padStart(2,'0'))) +'"></td><td><input data-steel-field="element" aria-label="Cấu kiện hoặc ghi chú" value="'+esc(row.element||'')+'"></td><td><select data-steel-field="diameter" aria-label="Đường kính">'+steelDiameters.map(d=>'<option value="'+d+'" '+(d===diameter?'selected':'')+'>'+d+'</option>').join('')+'</select></td><td><input data-steel-field="length" aria-label="Chiều dài một thanh" type="number" min="0" step="0.001" value="'+(Number(row.length)||0)+'"></td><td><input data-steel-field="count" aria-label="Số thanh" type="number" min="0" step="1" value="'+(Number(row.count)||0)+'"></td><td>'+fmt(totals.totalLength)+'</td><td>'+fmt(totals.unit)+'</td><td>'+fmt(totals.totalKg)+'</td><td><button class="steel-row-delete" data-delete-steel="'+id+'" aria-label="Xóa dòng">×</button></td></tr>'}).join('');
  updateSteelSummary();
}
function updateSteelRowDisplay(row,rowElement){
  const totals=steelRowTotals(row),cells=rowElement?.querySelectorAll('td');if(cells){cells[5].textContent=fmt(totals.totalLength);cells[6].textContent=fmt(totals.unit);cells[7].textContent=fmt(totals.totalKg)}updateSteelSummary();
}
function addSteelBar({length=0,count=1,diameter=12,mark='',element=''}={}){
  const next=steelBars.length+1;steelBars.push({id:'sb-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),mark:mark||'T'+String(next).padStart(2,'0'),element,length:Number(length)||0,count:Number(count)||0,diameter:Number(diameter)||12});renderSteelRows();persist();
}
function setPdfHint(message,error=false){const el=$('#steelMeasureHint');el.textContent=message;el.classList.toggle('is-error',error)}
function setPdfMode(mode){
  pdfMode=mode;pdfPoints=[];pdfMarkup?.classList.toggle('pdf-markup-idle',!mode);
  if(pdfMarkup)pdfMarkup.style.pointerEvents=mode?'auto':'none';
  if(mode==='calibrate')setPdfHint('Đang đặt tỷ lệ: bấm hai đầu của một kích thước đã biết trên bản vẽ.');
  else if(mode==='measure')setPdfHint('Đang đo: bấm hai đầu một đoạn thép. Sau điểm thứ hai sẽ tạo dòng khối lượng.');
  else setPdfHint('Chọn “Bắt đầu đo” rồi bấm lần lượt vào hai đầu đoạn thép.');
}
function updatePdfScaleStatus(){
  const scale=pdfPageCalibrations.get(pdfPageNumber)||0,el=$('#steelScaleStatus');
  if(scale){el.textContent='Đã hiệu chuẩn trang '+pdfPageNumber+' · 1 m ≈ '+fmt(1/scale)+' px trên trang';el.classList.add('is-set')}
  else{el.textContent='Chưa đặt tỷ lệ cho trang '+pdfPageNumber;el.classList.remove('is-set')}
}
async function loadPdfJs(){
  if(pdfjsModule)return pdfjsModule;
  pdfjsModule=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs');
  pdfjsModule.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs';
  return pdfjsModule;
}
async function renderPdfPage(){
  if(!pdfDocument)return;
  const token=++pdfRenderToken;$('#pdfTextStatus').textContent='Đang dựng trang và đọc lớp chữ…';
  try{
    const page=await pdfDocument.getPage(pdfPageNumber),base=page.getViewport({scale:1}),stage=$('#pdfStage'),dpr=Math.min(window.devicePixelRatio||1,2);
    const available=Math.max(260,stage.clientWidth-34),cssScale=Math.min(1.65,available/base.width)*pdfZoom,viewport=page.getViewport({scale:cssScale*dpr}),cssWidth=viewport.width/dpr,cssHeight=viewport.height/dpr;
    pdfCanvas.width=viewport.width;pdfCanvas.height=viewport.height;pdfCanvas.style.width=cssWidth+'px';pdfCanvas.style.height=cssHeight+'px';
    pdfMarkup.width=viewport.width;pdfMarkup.height=viewport.height;pdfMarkup.style.width=cssWidth+'px';pdfMarkup.style.height=cssHeight+'px';
    pdfStack.style.width=cssWidth+'px';pdfStack.style.height=cssHeight+'px';$('#pdfEmpty').hidden=true;pdfStack.hidden=false;
    await page.render({canvasContext:pdfCanvas.getContext('2d'),viewport}).promise;if(token!==pdfRenderToken)return;
    const textContent=await page.getTextContent(),text=textContent.items.map(item=>item.str).filter(Boolean).join(' ').replace(/\s{2,}/g,' ').trim();
    $('#pdfTextStatus').textContent=text?'Đọc được '+textContent.items.filter(item=>item.str).length+' đoạn chữ trên trang '+pdfPageNumber+'.':'Trang này không có lớp chữ chọn được; có thể là bản scan.';
    $('#pdfExtract').textContent=text?text.slice(0,7000)+(text.length>7000?'\n… (đã rút gọn phần xem trước)':''):'Không tìm thấy chữ máy đọc được. Anh vẫn có thể xem hình, hiệu chuẩn tỷ lệ và nhập/đo thủ công.';
    $('#pdfPageLabel').textContent=pdfPageNumber+' / '+pdfDocument.numPages;$('#steelPdfInfo').textContent=pdfDocument.numPages+' trang · Trang đang xem '+pdfPageNumber;
    updatePdfScaleStatus();drawPdfMarks();
  }catch(error){console.error('PDF render error',error);$('#pdfTextStatus').textContent='Không thể hiển thị trang PDF.';setPdfHint('Trình duyệt không đọc được trang này. Hãy thử xuất lại PDF rồi tải lên.',true)}
}
function pdfPointFromEvent(event){
  const rect=pdfMarkup.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height}
}
function normalizedDistance(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function drawPdfMarks(){
  if(!pdfMarkup)return;const ctx=pdfMarkup.getContext('2d'),w=pdfMarkup.width,h=pdfMarkup.height;ctx.clearRect(0,0,w,h);
  const marks=pdfPageMarks.get(pdfPageNumber)||[];
  marks.forEach(mark=>{const x1=mark.a.x*w,y1=mark.a.y*h,x2=mark.b.x*w,y2=mark.b.y*h;ctx.save();ctx.strokeStyle=mark.kind==='scale'?'#db9d3c':'#28a680';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=Math.max(2,w/900);ctx.setLineDash(mark.kind==='scale'?[8,6]:[]);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);for(const [x,y]of[[x1,y1],[x2,y2]]){ctx.beginPath();ctx.arc(x,y,Math.max(4,w/180),0,Math.PI*2);ctx.fill()}if(mark.label){ctx.font='bold '+Math.max(13,w/60)+'px sans-serif';ctx.fillText(mark.label,(x1+x2)/2+8,(y1+y2)/2-8)}ctx.restore()});
  if(pdfPoints.length===1){const p=pdfPoints[0];ctx.save();ctx.fillStyle='#d89e39';ctx.beginPath();ctx.arc(p.x*w,p.y*h,Math.max(5,w/160),0,Math.PI*2);ctx.fill();ctx.restore()}
}
async function handlePdfPoint(event){
  if(!pdfMode||!pdfDocument)return;const point=pdfPointFromEvent(event);
  if(!pdfPoints.length){pdfPoints=[point];drawPdfMarks();return}
  const first=pdfPoints[0],distanceFraction=normalizedDistance(first,point);pdfPoints=[];
  if(distanceFraction<.001){setPdfHint('Hai điểm quá gần nhau. Hãy chọn lại hai điểm cách xa hơn.',true);drawPdfMarks();return}
  const marks=pdfPageMarks.get(pdfPageNumber)||[];
  if(pdfMode==='calibrate'){
    const mm=Number($('#knownDistanceMm').value);if(!(mm>0)){setPdfHint('Nhập khoảng cách thực tế bằng mm trước khi chọn điểm.',true);setPdfMode('');return}
    pdfPageCalibrations.set(pdfPageNumber,distanceFraction/(mm/1000));marks.push({a:first,b:point,kind:'scale',label:fmt(mm)+' mm'});pdfPageMarks.set(pdfPageNumber,marks);setPdfMode('');updatePdfScaleStatus();setPdfHint('Đã hiệu chuẩn trang '+pdfPageNumber+'. Nên chọn đường kích thước dài, rõ và đúng đơn vị.');drawPdfMarks();return
  }
  const scale=pdfPageCalibrations.get(pdfPageNumber)||0;if(!scale){setPdfHint('Trang này chưa có tỷ lệ. Hãy hiệu chuẩn bằng kích thước đã biết trước.',true);setPdfMode('');return}
  const length=distanceFraction/scale,diameter=Number($('#defaultBarDiameter').value)||12,count=Math.max(1,Math.floor(Number($('#defaultBarCount').value)||1));
  const label=fmt(length)+' m · Ø'+diameter+' · '+count+' thanh';marks.push({a:first,b:point,kind:'measure',label});pdfPageMarks.set(pdfPageNumber,marks);
  addSteelBar({length:Number(length.toFixed(3)),count,diameter,element:'Đo từ PDF · trang '+pdfPageNumber});
  setPdfMode('');setPdfHint('Đã thêm '+fmt(length)+' m/thanh × '+count+' thanh Ø'+diameter+'. Kiểm tra dòng mới ở bảng bên dưới.');drawPdfMarks();
}
async function openSteelPdf(file){
  if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){toast('Anh hãy chọn một file PDF.');return}
  if(file.size>60*1024*1024){toast('File vượt quá 60 MB. Hãy xuất PDF nhẹ hơn rồi thử lại.');return}
  $('#steelUpload').hidden=true;$('#steelWorkspace').hidden=false;$('#steelFileName').textContent=file.name;$('#pdfTextStatus').textContent='Đang mở PDF…';$('#pdfExtract').textContent='Đang đọc nội dung chữ của trang…';navigate('steel');
  try{
    if(pdfDocument){await pdfDocument.destroy();pdfDocument=null}
    pdfPageCalibrations=new Map();pdfPageMarks=new Map();pdfPageNumber=1;pdfZoom=1;setPdfMode('');
    const lib=await loadPdfJs(),bytes=new Uint8Array(await file.arrayBuffer());pdfDocument=await lib.getDocument({data:bytes}).promise;
    $('#steelPdfInfo').textContent=pdfDocument.numPages+' trang';$('#pdfPageLabel').textContent='1 / '+pdfDocument.numPages;await renderPdfPage();
  }catch(error){console.error('PDF load error',error);$('#pdfTextStatus').textContent='Không mở được file PDF.';$('#pdfExtract').textContent='File có thể bị lỗi, được mã hóa bằng mật khẩu hoặc trình duyệt không tải được thư viện đọc PDF. Hãy thử một PDF khác.';toast('Không mở được PDF. Kiểm tra file rồi thử lại.')}
}
$('#chooseSteelPdf').addEventListener('click',()=>$('#steelPdfInput').click());
$('#steelUploadButton').addEventListener('click',()=>$('#steelPdfInput').click());
$('#replaceSteelPdf').addEventListener('click',()=>$('#steelPdfInput').click());
$('#steelPdfInput').addEventListener('change',e=>{const file=e.target.files?.[0];if(file)openSteelPdf(file);e.target.value=''});
$('#removeSteelPdf').addEventListener('click',async()=>{if(pdfDocument){await pdfDocument.destroy();pdfDocument=null}setPdfMode('');pdfPageCalibrations.clear();pdfPageMarks.clear();$('#steelWorkspace').hidden=true;$('#steelUpload').hidden=false;$('#pdfCanvasStack').hidden=true;$('#pdfEmpty').hidden=false;$('#pdfEmpty').textContent='Bản vẽ sẽ xuất hiện tại đây.';$('#pdfTextStatus').textContent='Chọn một file PDF để bắt đầu.';$('#pdfExtract').textContent='Chọn một file PDF để bắt đầu.'});
$('#pdfPrev').addEventListener('click',()=>{if(pdfDocument&&pdfPageNumber>1){pdfPageNumber--;setPdfMode('');renderPdfPage()}});
$('#pdfNext').addEventListener('click',()=>{if(pdfDocument&&pdfPageNumber<pdfDocument.numPages){pdfPageNumber++;setPdfMode('');renderPdfPage()}});
$('#pdfZoomIn').addEventListener('click',()=>{pdfZoom=Math.min(2.5,pdfZoom*1.2);renderPdfPage()});
$('#pdfZoomOut').addEventListener('click',()=>{pdfZoom=Math.max(.55,pdfZoom/1.2);renderPdfPage()});
$('#setScaleMode').addEventListener('click',()=>{if(!pdfDocument){toast('Tải bản vẽ PDF lên trước.');return}if(!(Number($('#knownDistanceMm').value)>0)){setPdfHint('Nhập khoảng cách thực tế (mm), ví dụ 6000, rồi bấm nút hiệu chuẩn.',true);$('#knownDistanceMm').focus();return}setPdfMode('calibrate')});
$('#measureMode').addEventListener('click',()=>{if(!pdfDocument){toast('Tải bản vẽ PDF lên trước.');return}if(!(pdfPageCalibrations.get(pdfPageNumber)>0)){setPdfHint('Hiệu chuẩn tỷ lệ cho trang đang xem trước khi đo.',true);return}setPdfMode('measure')});
$('#cancelPdfMode').addEventListener('click',()=>setPdfMode(''));
pdfMarkup.addEventListener('click',handlePdfPoint);
$('#addSteelRow').addEventListener('click',()=>{addSteelBar({diameter:12,count:1,element:''});$('#steelRows tr:last-child input[data-steel-field="length"]')?.focus()});
$('#steelRows').addEventListener('input',e=>{const field=e.target.dataset.steelField,rowElement=e.target.closest('[data-steel-row]');if(!field||!rowElement)return;const row=steelBars.find(item=>item.id===rowElement.dataset.steelRow);if(!row)return;row[field]=field==='diameter'||field==='length'||field==='count'?Number(e.target.value)||0:e.target.value;updateSteelRowDisplay(row,rowElement);persist()});
$('#steelRows').addEventListener('change',e=>{if(e.target.dataset.steelField){const rowElement=e.target.closest('[data-steel-row]'),row=steelBars.find(item=>item.id===rowElement?.dataset.steelRow);if(row){row[e.target.dataset.steelField]=Number(e.target.value)||0;updateSteelRowDisplay(row,rowElement);persist()}}});
$('#steelRows').addEventListener('click',e=>{const button=e.target.closest('[data-delete-steel]');if(!button)return;steelBars=steelBars.filter(row=>row.id!==button.dataset.deleteSteel);renderSteelRows();persist()});
$('#exportSteelCsv').addEventListener('click',()=>{
  if(!steelBars.length){toast('Bảng chưa có dòng thép để xuất.');return}
  const rows=[['Ký hiệu','Cấu kiện / ghi chú','Đường kính (mm)','Chiều dài 1 thanh (m)','Số thanh','Tổng chiều dài (m)','Trọng lượng đơn vị (kg/m)','Khối lượng (kg)'],...steelBars.map(row=>{const t=steelRowTotals(row);return[row.mark,row.element,row.diameter,t.length,t.count,t.totalLength,t.unit,t.totalKg]})];
  const csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download='QS-Pro-'+project.name.replace(/[^\p{L}\p{N}-]+/gu,'-')+'-Thep.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500);toast('Đã xuất bảng khối lượng thép ra CSV.')
});
renderSteelRows();

