const seed = [
  { code:'CP.01', category:'Công tác đất', description:'Đào đất móng bằng máy, đất cấp II', unit:'m³', quantity:148.5, price:92000, formula:'Dài × Rộng × Sâu × Số lượng', dims:'15 × 11 × 0,9 × 1', note:'Đã trừ thể tích đài móng' },
  { code:'BT.01', category:'Bê tông', description:'Bê tông lót móng M100', unit:'m³', quantity:42.5, price:1250000, formula:'Dài × Rộng × Sâu × Số lượng', dims:'42,5 × 1', note:'Theo bản vẽ KC-03' },
  { code:'BT.02', category:'Bê tông', description:'Bê tông móng M300', unit:'m³', quantity:186.2, price:1680000, formula:'Theo cấu kiện', dims:'Tổng hợp đài móng M1–M8', note:'Chưa gồm bê tông cổ cột' },
  { code:'CT.01', category:'Cốt thép', description:'Cốt thép móng CB400-V', unit:'kg', quantity:12480, price:18900, formula:'Chiều dài × Trọng lượng đơn vị', dims:'Tổng hợp thống kê thép', note:'Đã tính nối chồng theo chi tiết' },
  { code:'VK.01', category:'Ván khuôn', description:'Ván khuôn móng', unit:'m²', quantity:326.4, price:285000, formula:'Chu vi × Chiều cao × Số cấu kiện', dims:'Tổng hợp các đài móng', note:'Diện tích tiếp xúc bê tông' }
];
const demoMode = location.protocol === 'file:' || new URLSearchParams(location.search).has('demo');
const config=window.QS_PRO_SUPABASE_CONFIG||{},configured=/^https:\/\/.+/.test(config.url||'')&&(config.anonKey||'').length>20;
const supabaseClient=configured&&window.supabase?.createClient?window.supabase.createClient(config.url,config.anonKey):null;
let user = null, passwordRecovery = new URLSearchParams(location.hash.slice(1)).get('type')==='recovery', items = read('qspro-items', seed), project = read('qspro-project', {name:'Riverside Residence', type:'Nhà ở cao tầng', location:'TP. Hồ Chí Minh'}), settings = read('qspro-settings', {waste:0, overhead:5, contingency:2, vat:8}), filterText = '', activeCategory = 'Tất cả', saveTimer;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(Number(n)||0),cash=n=>fmt(Math.round(Number(n)||0)),total=()=>items.reduce((s,x)=>s+(+x.quantity||0)*(+x.price||0),0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function showMessage(text,error=false){const el=$('#authMessage');el.textContent=text;el.classList.toggle('error',error);el.hidden=false}
async function saveCloud(){if(!user||demoMode)return;const {error}=await supabaseClient.from('qspro_workspaces').upsert({user_id:user.id,workspace:{items,project,settings},updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)toast('Chưa đồng bộ được dữ liệu. Hãy kiểm tra kết nối rồi thử lại.')}
function persist(){if(demoMode){localStorage.setItem('qspro-items',JSON.stringify(items));localStorage.setItem('qspro-project',JSON.stringify(project));localStorage.setItem('qspro-settings',JSON.stringify(settings));return}if(!user)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,500)}
function navigate(page){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===`page-${page}`));document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.page===page));const names={overview:'Tổng quan',takeoff:'Bóc tách khối lượng',skills:'Kỹ năng QS',library:'Thư viện tài liệu'};$('#crumb').textContent=names[page];history.replaceState(null,'',`#${page}`);window.scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(e=>e.addEventListener('click',()=>navigate(e.dataset.page)));
function render(){
  $('#projectTitle').textContent=project.name;$('#projectMeta').textContent=`${project.type} · ${project.location}`;
  const categories=['Tất cả',...new Set(items.map(i=>i.category||'Khác'))];$('#categoryFilters').innerHTML=categories.map(c=>`<button class="filter-chip ${activeCategory===c?'selected':''}" data-category="${esc(c)}">${esc(c)} <span>${c==='Tất cả'?items.length:items.filter(i=>i.category===c).length}</span></button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;render()});
  const shown=items.map((x,i)=>({...x,_i:i})).filter(x=>(activeCategory==='Tất cả'||x.category===activeCategory)&&(`${x.code} ${x.description} ${x.category}`.toLowerCase().includes(filterText)));
  $('#boqBody').innerHTML=shown.map(x=>`<tr><td class="code-cell"><span>${esc(x.code)}</span></td><td><div class="work-name">${esc(x.description)}</div><div class="work-detail">${esc(x.note||'')}</div></td><td><span class="category-pill">${esc(x.category||'Khác')}</span></td><td class="unit-cell">${esc(x.unit)}</td><td class="numeric">${fmt(x.quantity)}</td><td class="numeric">${cash(x.price)}</td><td class="numeric amount-cell">${cash(x.quantity*x.price)}</td><td><button class="row-more" title="Thao tác" data-row="${x._i}">•••</button></td></tr>`).join('');$('#emptyState').hidden=shown.length!==0;
  const sub=total(),waste=sub*(+settings.waste||0)/100,overhead=(sub+waste)*(+settings.overhead||0)/100,contingency=(sub+waste+overhead)*(+settings.contingency||0)/100,beforeVat=sub+waste+overhead+contingency,vat=beforeVat*(+settings.vat||0)/100;
  $('#boqCount').textContent=String(items.length).padStart(2,'0');$('#totalItems').innerHTML=`${String(items.length).padStart(2,'0')} <small>hạng mục</small>`;$('#boqTotal').textContent=cash(sub);$('#grandTotal').textContent=cash(beforeVat+vat);$('#grandTotalCopy').textContent=cash(beforeVat+vat);$('#subtotal').textContent=cash(sub);$('#wasteTotal').textContent=cash(waste);$('#overheadTotal').textContent=cash(overhead);$('#contingencyTotal').textContent=cash(contingency);$('#vatTotal').textContent=cash(vat);$('#totalCost').innerHTML=sub?`${cash(sub)} <small>VND</small>`:'—';$('#scopeCount').textContent=items.length;$('#costBar').style.width=(sub?Math.max(12,Math.min(100,100*sub/(sub+150000000))):0)+'%';
  for(const key of ['waste','overhead','contingency','vat']){const input=$(`[data-setting="${key}"]`);if(input&&document.activeElement!==input)input.value=settings[key]}persist();
}
function setAuthMode(mode){const signup=mode==='signup',recovery=mode==='recovery';document.querySelector('.auth-mode').hidden=recovery;$('#resetPassword').hidden=recovery;document.querySelectorAll('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#authHeading').textContent=recovery?'Đặt mật khẩu mới':signup?'Tạo tài khoản QS Pro':'Đăng nhập workspace';$('#authDescription').textContent=recovery?'Chọn mật khẩu mới để bảo vệ tài khoản của bạn.':signup?'Tạo không gian riêng cho dự án và dữ liệu QS của bạn.':'Dùng email và mật khẩu để tiếp tục công việc.';$('#authSubmit').innerHTML=recovery?'Lưu mật khẩu mới <span>→</span>':signup?'Tạo tài khoản <span>→</span>':'Đăng nhập <span>→</span>';$('#authForm [name="password"]').autocomplete=signup||recovery?'new-password':'current-password';$('#authMessage').hidden=true;}
document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));
async function enterWorkspace(authUser){if(!demoMode&&authUser&&user?.id===authUser.id&&!$('#appShell').hidden)return;user=authUser;$('#authScreen').hidden=true;$('#appShell').hidden=false;$('#profileEmail').textContent=demoMode?'Bản demo trên thiết bị này':user.email;$('#profileName').textContent=demoMode?'Giám đốc dự án':'Chủ workspace';if(!demoMode){const {data,error}=await supabaseClient.from('qspro_workspaces').select('workspace').eq('user_id',user.id).maybeSingle();if(error){await supabaseClient.auth.signOut();user=null;$('#appShell').hidden=true;$('#authScreen').hidden=false;showMessage('Không tải được dữ liệu workspace. Kiểm tra cấu hình bảng và chính sách bảo mật rồi thử lại.',true);return}if(data?.workspace){items=data.workspace.items||seed;project=data.workspace.project||project;settings=data.workspace.settings||settings}else persist()}render();const start=location.hash.slice(1);if(['overview','takeoff','skills','library'].includes(start))navigate(start)}
if(demoMode){enterWorkspace(null)}else{ $('#authScreen').hidden=false;if(!configured||!supabaseClient){$('#authSetup').hidden=false;$('#authSubmit').disabled=true;$('#resetPassword').disabled=true;}else{supabaseClient.auth.getSession().then(({data})=>{if(passwordRecovery){$('#authScreen').hidden=false;setAuthMode('recovery');if(data.session)$('#authForm [name="email"]').value=data.session.user.email||''}else if(data.session)enterWorkspace(data.session.user)});supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session&&$('#appShell').hidden&&!passwordRecovery)setTimeout(()=>enterWorkspace(session.user),0);else if(!session){user=null;$('#appShell').hidden=true;$('#authScreen').hidden=false}});if(passwordRecovery)setAuthMode('recovery')}}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();if(!configured){showMessage('Hệ thống đăng nhập chưa được cấu hình. Chưa có mật khẩu nào được gửi.',true);return}const form=new FormData(e.currentTarget),email=String(form.get('email')).trim(),password=String(form.get('password')),signup=document.querySelector('[data-auth-mode="signup"]').classList.contains('active'),button=$('#authSubmit');button.disabled=true;button.textContent=passwordRecovery?'Đang cập nhật…':signup?'Đang tạo tài khoản…':'Đang đăng nhập…';$('#authMessage').hidden=true;try{if(passwordRecovery){const {error}=await supabaseClient.auth.updateUser({password});if(error)throw error;passwordRecovery=false;history.replaceState(null,'',location.pathname);setAuthMode('signin');showMessage('Đã cập nhật mật khẩu. Đang mở workspace của bạn.');const {data}=await supabaseClient.auth.getSession();if(data.session)await enterWorkspace(data.session.user)}else{const result=signup?await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabaseClient.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signup&&!result.data.session)showMessage('Đã nhận yêu cầu đăng ký. Hãy mở email xác nhận để kích hoạt tài khoản QS Pro.');else if(result.data.user)await enterWorkspace(result.data.user)}}catch(err){showMessage(err.message||'Không thể đăng nhập. Hãy kiểm tra email và mật khẩu.',true)}finally{button.disabled=false;button.innerHTML=passwordRecovery?'Lưu mật khẩu mới <span>→</span>':signup?'Tạo tài khoản <span>→</span>':'Đăng nhập <span>→</span>'}});
$('#resetPassword').addEventListener('click',async()=>{const email=$('#authForm [name="email"]').value.trim();if(!email){showMessage('Nhập email của bạn trước để nhận liên kết đặt lại mật khẩu.',true);return}if(!configured){showMessage('Dịch vụ tài khoản chưa được kết nối.',true);return}const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin});showMessage(error?error.message:'Nếu email tồn tại, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.',!!error)});
$('#signOut').addEventListener('click',async()=>{if(demoMode){toast('Bản demo cục bộ không có tài khoản để đăng xuất.');return}clearTimeout(saveTimer);await saveCloud();await supabaseClient.auth.signOut()});
$('#searchBOQ').addEventListener('input',e=>{filterText=e.target.value.toLowerCase().trim();render()});
$('#addItem').addEventListener('click',()=>{$('#itemForm').reset();$('#itemForm [name="quantity"]').value=1;$('#itemForm [name="price"]').value=0;$('#itemForm [name="count"]').value=1;$('#formulaPreview').textContent='Nhập kích thước để xem phép tính.';$('#itemDialog').showModal()});
$('#itemForm').addEventListener('input',e=>{if(['length','width','height','count','unit'].includes(e.target.name)){const f=new FormData(e.currentTarget),l=+f.get('length')||1,w=+f.get('width')||1,h=+f.get('height')||1,n=+f.get('count')||1,u=f.get('unit'),q=u==='m²'?l*w*n:u==='m'||u==='kg'?l*n:l*w*h*n,expression=u==='m²'?`${fmt(l)} × ${fmt(w)} × ${fmt(n)}`:u==='m'||u==='kg'?`${fmt(l)} × ${fmt(n)}`:`${fmt(l)} × ${fmt(w)} × ${fmt(h)} × ${fmt(n)}`;$('#formulaPreview').textContent=`${expression} = ${fmt(q)} ${u}`}});
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),category=f.get('category'),prefix=({'Công tác đất':'CP','Bê tông':'BT','Cốt thép':'CT','Ván khuôn':'VK','Hoàn thiện':'HT','MEP':'MEP'})[category]||'KH',sequence=items.filter(x=>x.category===category).length+1,l=+f.get('length')||1,w=+f.get('width')||1,h=+f.get('height')||1,n=+f.get('count')||1,u=f.get('unit'),quantity=f.get('quantity')?+f.get('quantity'):u==='m²'?l*w*n:u==='m'||u==='kg'?l*n:l*w*h*n;items.push({code:`${prefix}.${String(sequence).padStart(2,'0')}`,category,description:f.get('description'),unit:u,quantity,price:+f.get('price')||0,formula:f.get('formula')||'Kích thước × Số lượng',dims:`${fmt(l)} × ${fmt(w)} × ${fmt(h)} × ${fmt(n)}`,note:f.get('note')||''});$('#itemDialog').close();render();toast('Đã thêm công tác vào bảng khối lượng.')});
$('#boqBody').addEventListener('click',e=>{const b=e.target.closest('[data-row]');if(!b)return;const i=+b.dataset.row,choice=prompt(`Thao tác với ${items[i].code}: nhập “x” để xóa, hoặc nhập đơn giá mới.`);if(choice===null)return;if(choice.trim().toLowerCase()==='x'){if(confirm('Xóa hạng mục này khỏi BOQ?')){items.splice(i,1);render();toast('Đã xóa hạng mục.')}return}const price=Number(choice);if(Number.isFinite(price)&&price>=0){items[i].price=price;render();toast('Đã cập nhật đơn giá.')}else toast('Nhập “x” để xóa hoặc nhập đơn giá hợp lệ.')});
document.querySelectorAll('[data-setting]').forEach(input=>input.addEventListener('input',()=>{settings[input.dataset.setting]=+input.value||0;render()}));
$('#exportCsv').addEventListener('click',()=>{const rows=[['Mã hiệu','Nhóm công tác','Mô tả','Đơn vị','Khối lượng','Đơn giá (VND)','Thành tiền (VND)','Cách tính','Ghi chú'],...items.map(x=>[x.code,x.category,x.description,x.unit,x.quantity,x.price,x.quantity*x.price,x.formula,x.note])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`QS-Pro-${project.name.replace(/[^\p{L}\p{N}-]+/gu,'-')}-BOQ.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Đã xuất BOQ kèm nhóm, ghi chú và cách tính.')});
$('#newProject').addEventListener('click',()=>{const name=prompt('Tên dự án mới:','Dự án mới');if(!name?.trim())return;const locationName=prompt('Địa điểm dự án:','TP. Hồ Chí Minh')||'Chưa cập nhật';project={name:name.trim(),type:'Dự án xây dựng',location:locationName};items=[];activeCategory='Tất cả';navigate('takeoff');render();toast('Đã tạo workspace dự án.')});
$('#measureGuide').addEventListener('click',()=>toast('Quy trình: xác nhận phiên bản bản vẽ → phân nhóm công tác → đo bóc cấu kiện → ghi rõ giả định → kiểm tra chéo.'));
$('#termsGuide').addEventListener('click',()=>toast('BOQ: Bảng khối lượng · BUA: Tổng diện tích sàn · VO: Phát sinh hợp đồng · QS: Kỹ sư khối lượng.'));
$('#drawingInfo').addEventListener('click',()=>toast('Bản vẽ mẫu KC-03 · Rev. B. Phiên bản cần được xác nhận theo hồ sơ phát hành thực tế.'));
$('#today').textContent=new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date());
